steps:
  # pull last image to benifit from cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/blog-ui:latest || exit 0

  # run the docker build command
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-f', './Dockerfile.prod',
        '-t', 'gcr.io/$PROJECT_ID/blog-ui:latest',
        '--cache-from', 'gcr.io/$PROJECT_ID/blog-ui:latest',
        '.'
    ]

# push the created image with the following tags
images: ['gcr.io/$PROJECT_ID/blog-ui:latest']
