steps:

  # pull last image to benifit from cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'load-cached-images'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/blog-ui:latest || exit 0

  # Docker build, but target test
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-for-test'
    args: [
        'build',
        '-f', './Dockerfile',
        '-t', 'gcr.io/$PROJECT_ID/blog-ui-test:$COMMIT_SHA',
        '--target', 'test',
        '--cache-from', 'gcr.io/$PROJECT_ID/blog-ui:latest',
        '.'
    ]

  # Docker build production image, using test image as cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-for-prod'
    waitFor: ['build-for-test']
    args: [
        'build',
        '-f', './Dockerfile',
        '-t', 'gcr.io/$PROJECT_ID/blog-ui:$COMMIT_SHA',
        '--cache-from', 'gcr.io/$PROJECT_ID/blog-ui-test:$COMMIT_SHA',
        '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'lint'
    waitFor: ['build-for-test']
    args: [
    'run', 'gcr.io/$PROJECT_ID/blog-ui-test:$COMMIT_SHA', 'golangci-lint', 'run'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'test'
    waitFor: ['build-for-test']
    args: [
    'run', 'gcr.io/$PROJECT_ID/blog-ui-test:$COMMIT_SHA', 'go', 'test', './...'
    ]

    # might need this
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push docker image'
    waitFor: ['test', 'lint']
    args: ['push', 'gcr.io/$PROJECT_ID/blog-ui:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'trigger environment update'
    args: ['set', 'image', 'deployment/blog-ui', 'blog-ui=gcr.io/$PROJECT_ID/blog-ui:$COMMIT_SHA']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=blog-cluster-europe-west'

# push the created image with the following tags
tags: ['latest', '$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/blog-ui']

