on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Test, Build and Deploy

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE: blog-ui

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GKE_SA_EMAIL }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

           # Push the Docker image to Google Container Registry
    - name: Pull
      run: |-
        docker pull "gcr.io/$PROJECT_ID/$IMAGE:latest" || exit 0

    - name: Build-test
      run: docker build -t blog-ui --target test .

    - name: Lint
      run: docker run blog-ui:latest golangci-lint run

    - name: Test
      run: docker run blog-ui:latest go test ./...

    - name: Build
      run: docker build -t blog-ui .
