name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start
      run: echo "hi"

    - name: Build
      run: DOCKER_BUILDKIT=1 docker build -t blog-ui --target test .

    - name: Lint
      run: docker run blog-ui:latest golangci-lint run

    - name: Test
      run: docker run blog-ui:latest go test ./...
