on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: docker build -t blog-ui --target test .
      env:
        DOCKER_BUILDKIT: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: docker run blog-ui:latest go test ./...

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: docker run blog-ui:latest golangci-lint run
