on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build-test
      run: docker build -t blog-ui --target test .

    - name: Lint
      run: docker run blog-ui:latest golangci-lint run

    - name: Test
      run: docker run blog-ui:latest go test ./...

    - name: Build
      run: docker build -t blog-ui .
